NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

#How to install scipy and numpy

In [7]:
!pip install numpy



To install the dependencies open the terminal and type the following commands:

sudo apt-get update  
sudo apt-get install python-numpy 
python-scipy python-matplotlibipythonipythonnotebook python-pandas 
python-sympy python-nose

Operations using NumPy

Using NumPy, a developer can perform the following operations −

    Mathematical and logical operations on arrays.

    Fourier transforms and routines for shape manipulation.

    Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.


NumPy is often used along with packages like SciPy (Scientific Python) and Mat−plotlib (plotting library). This combination is widely used as a replacement for MatLab, a popular platform for technical computin

### Simple and logical examples

In [1]:
import numpy as np 
a = np.array([1,2,3]) 
print(a)

[1 2 3]


In [2]:
# more than one dimensions 
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
print (a)

[[1 2]
 [3 4]]


In [3]:
# minimum dimensions 
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print (a)

[[1 2 3 4 5]]


In [8]:
# dtype parameter 
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[ 1.+0.j  2.+0.j  3.+0.j]


### Data Types & Description
NumPy numerical types are instances of dtype (data-type) objects, each having unique characteristics.

1 	
bool_

Boolean (True or False) stored as a byte

2 	

int_

Default integer type (same as C long; normally either int64 or int32)

3 	

intc

Identical to C int (normally int32 or int64)

4 	

intp

Integer used for indexing (same as C ssize_t; normally either int32 or int64)

5 	

int8

Byte (-128 to 127)

6 	

int16

Integer (-32768 to 32767)

7 	

int32

Integer (-2147483648 to 2147483647)

8 	

int64

Integer (-9223372036854775808 to 9223372036854775807)

9 	

uint8

Unsigned integer (0 to 255)

10 	

uint16

Unsigned integer (0 to 65535)

11 	

uint32

Unsigned integer (0 to 4294967295)

12 	

uint64

Unsigned integer (0 to 18446744073709551615)

13 	

float_

Shorthand for float64

14 	

float16

Half precision float: sign bit, 5 bits exponent, 10 bits mantissa

15 	

float32

Single precision float: sign bit, 8 bits exponent, 23 bits mantissa

16 	

float64

Double precision float: sign bit, 11 bits exponent, 52 bits mantissa

17 	

complex_

Shorthand for complex128

18 	

complex64

Complex number, represented by two 32-bit floats (real and imaginary components)

19 	

complex128

Complex number, represented by two 64-bit floats (real and imaginary components)




#A dtype object is constructed using the following syntax 

numpy.dtype(object, align, copy)



    Object − To be converted to data type object

    Align − If true, adds padding to the field to make it similar to C-struct

    Copy − Makes a new copy of dtype object. If false, the result is reference to builtin data type object


### Data types examples

In [10]:
# using array-scalar type 
import numpy as np 
dt = np.dtype(np.int32) 
print (dt)

int32


In [9]:

dt = np.dtype('i4')
print(dt) 

int32


In [11]:
# using endian notation 
 
dt = np.dtype('>i4') 
print(dt)

>i4


In [12]:
# first create structured data type 

dt = np.dtype([('age',np.int8)]) 
print(dt) 

[('age', 'i1')]


In [13]:
# now apply it to ndarray object 


dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a)

[(10,) (20,) (30,)]


In [14]:
# file name can be used to access content of age column 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print (a['age'])

[10 20 30]


In [15]:
#string field 'name', an integer field 'age' and a float field 'marks'. This dtype is applied to ndarray object.


student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
print(student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [20]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(a)

[(b'abc', 21,  50.) (b'xyz', 18,  75.)]


### ndarray.shape

This array attribute returns a tuple consisting of array dimensions. It can also be used to resize the array.

In [21]:
a = np.array([[1,2,3],[4,5,6]]) 
print(a.shape)

(2, 3)


In [30]:
# this resizes the ndarray 
a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print(a)

array([[ 0,  0, -1],
       [-4, -4,  6]])

In [ ]:
# NumPy also provides a reshape function to resize an array.

In [25]:
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2) 
print(b)

[[1 2]
 [3 4]
 [5 6]]


### ndarray.ndim

This array attribute returns the number of array dimen

In [26]:
# an array of evenly spaced numbers 
a = np.arange(24) 
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [35]:
# this is one dimensional array 
 
a = np.arange(36) 
a.ndim  
# now reshape it 
b = a.reshape(2,2,3,3) 
print(b )
# b is having three dimensions

[[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]]

  [[ 9 10 11]
   [12 13 14]
   [15 16 17]]]


 [[[18 19 20]
   [21 22 23]
   [24 25 26]]

  [[27 28 29]
   [30 31 32]
   [33 34 35]]]]


### numpy.itemsize

This array attribute returns the length of each element of array in bytes.

In [36]:
# dtype of array is int8 (1 byte) 
x = np.array([1,2,3,4,5], dtype = np.int8) 
print(x.itemsize)

1


In [37]:
# dtype of array is now float32 (4 bytes) 
x = np.array([1,2,3,4,5], dtype = np.float32) 
print (x.itemsize)

4


In [38]:
# The following example shows the current values of flags.
x = np.array([1,2,3,4,5]) 
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


### numpy.empty

It creates an uninitialized array of specified shape and dtype. It uses the following constructor −

numpy.empty(shape, dtype = float, order = 'C')

Shape of an empty array in int or tuple of int
Dtype Desired output data type. Optional
Order

'C' for C-style row-major array, 'F' for FORTRAN style column-major array


In [45]:
x = np.empty([3,2], dtype = int) 
print(x)

[[1 2]
 [3 4]
 [5 6]]


### numpy.zeros

Returns a new array of specified size, filled with zeros.

numpy.zeros(shape, dtype = float, order = 'C')


In [46]:
x = np.zeros(5) 
print(x)
x = np.zeros((5,), dtype = np.int)
print(x)
x = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(x)

[ 0.  0.  0.  0.  0.]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


### numpy.ones

Returns a new array of specified size and type, filled with ones.

numpy.ones(shape, dtype = None, order = 'C')


In [47]:
x = np.ones(5) 
print(x)

[ 1.  1.  1.  1.  1.]


In [48]:
x = np.ones([2,2], dtype = int) 
print(x)

[[1 1]
 [1 1]]


### numpy.asarray

This function is similar to numpy.array except for the fact that it has fewer parameters. This routine is useful for converting Python sequence into ndarray.

numpy.asarray(a, dtype = None, order = None)


In [49]:
x = [1,2,3] 
a = np.asarray(x) 
print(a)

[1 2 3]


In [50]:
x = [1,2,3]
a = np.asarray(x, dtype = float) 
print (a)

[ 1.  2.  3.]


In [51]:
x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print(a)

[(1, 2, 3) (4, 5)]


The following examples show how to use the built-in range() function to return a list object. An iterator of this list is used to form an ndarray object.


In [52]:
import numpy as np 
list = range(5) 
print(list)

range(0, 5)


In [53]:
import numpy as np 
list = range(5) 
it = iter(list) 
# use iterator to create ndarray 
x = np.fromiter(it, dtype = float) 
print(x)

[ 0.  1.  2.  3.  4.]


### numpy.arange

This function returns an ndarray object containing evenly spaced values within a given range. The format of the function is as follows −

numpy.arange(start, stop, step, dtype)


In [3]:
import numpy as np 
x = np.arange(5) 
print (x)
x = np.arange(5, dtype = float)
print (x)
x = np.arange(10,20,1) 
print (x)

[0 1 2 3 4]
[ 0.  1.  2.  3.  4.]
[10 11 12 13 14 15 16 17 18 19]


### numpy.linspace

This function is similar to arange() function. In this function, instead of step size, the number of evenly spaced values between the interval is specified. The usage of this function is as follows −

numpy.linspace(start, stop, num, endpoint, retstep, dtype)


In [6]:
import numpy as np 
x = np.linspace(10,20,10, dtype = int) 
print (x)

[10 11 12 13 14 15 16 17 18 20]


In [9]:
# endpoint set to false 
x = np.linspace(10,20, 6, endpoint = False) 
print (x)

[ 10.          11.66666667  13.33333333  15.          16.66666667
  18.33333333]


In [10]:
import numpy as np 

x = np.linspace(1,2,5, retstep = True) 
print(x) 
# retstep here is 0.25

(array([ 1.  ,  1.25,  1.5 ,  1.75,  2.  ]), 0.25)


### numpy.logspace

This function returns an ndarray object that contains the numbers that are evenly spaced on a log scale. Start and stop endpoints of the scale are indices of the base, usually 10.

numpy.logspace(start, stop, num, endpoint, base, dtype)


In [11]:
import numpy as np 
# default base is 10 
a = np.logspace(1.0, 2.0, num = 10) 
print (a)

[  10.           12.91549665   16.68100537   21.5443469    27.82559402
   35.93813664   46.41588834   59.94842503   77.42636827  100.        ]


In [ ]:
a = np.logspace(1,10,num = 10, base = 2) 
print (a)

As mentioned earlier, items in ndarray object follows zero-based index. Three types of indexing methods are available − field access, basic slicing and advanced indexing.

In [ ]:
import numpy as np 
a = np.arange(10) 
s = slice(2,7,2) 
print(a[s])

In [ ]:
a = np.arange(10) 
b = a[2:7:2] 
print(b)

In [ ]:
a = np.arange(10) 
b = a[5] 
print(b)

In [ ]:
a = np.arange(10) 
print(a[2:])

In [ ]:
# slice items between indexes 

a = np.arange(10) 
print(a[2:5])

In [ ]:
##The above description applies to multi-dimensional ndarray too.
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)  

# slice items starting from index
print('Now we will slice the array from the index a[1:]') 
print(a[1:])

In [ ]:
# array to begin with 
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print ('Our array is:' )
print (a) 
print ('\n') 

# this returns array of items in the second column 
print ('The items in the second column are:')  
print (a[...,1]) 
print ('\n')  

# Now we will slice all items from the second row 
print ('The items in the second row are:' )
print (a[1,...]) 
print ('\n' ) 

# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:') 
print (a[...,1:])

### NumPy - Advanced Indexing

In [ ]:
import numpy as np 

x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print(y)

The selection includes elements at (0,0), (1,1) and (2,0) from the first array.

In the following example, elements placed at corners of a 4X3 array are selected. The row indices of selection are [0, 0] and [3,3] whereas the column indices are [0,2] and [0,2]

In [ ]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print('Our array is:' )
print (x) 
print ('\n') 

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
   
print('The corner elements of this array are:') 
print(y)

In [ ]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print('Our array is:') 
print(x) 
print('\n')  

# slicing 
z = x[1:4,1:3] 

print('After slicing, our array becomes:') 
print (z) 
print ('\n')  

# using advanced index for column 
y = x[1:4,[1,2]] 

print('Slicing using advanced index for column:') 
print(y)

### Boolean Array Indexing

This type of advanced indexing is used when the resultant object is meant to be the result of Boolean operations, such as comparison operators.

In [ ]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print ('Our array is:') 
print (x )
print ('\n')  

# Now we will print the items greater than 5 
print ('The items greater than 5 are:') 
print (x[x > 5])

In [ ]:
import numpy as np 
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
print(a[np.isnan(a)])

In [ ]:
import numpy as np 
a = np.array([1, 2+6j, 5, 3.5+5j]) 
print (a[np.iscomplex(a)])

The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.

In [ ]:
import numpy as np 

a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print(c)